<?php
/**
 * @since 1.0.0
 * @version 2.0
 */
CSF::createSection(ZETA_OPTIONS,
    array(
        'title'  => __z('Comments'),
        'parent' => 'settings',
        'icon'   => 'fa fa-minus',
        'fields' => array(
            array(
                'id'      => 'comments',
                'type'    => 'radio',
                'title'   => __z('Comments system'),
                'default' => 'wp',
                'options' => array(
                    'wp' => __z('WordPress'),
                    'fb' => __z('Facebook'),
                    'dq' => __z('Disqus'),
                    'nn' => __z('None')
                )
            ),
            array(
                'id'    => 'commentspage',
                'type'  => 'switcher',
                'title' => __z('Comments on pages'),
                'label' => __z('Allow comments on all pages?'),
                'dependency' => array('comments', '!=', 'nn')
            ),
            array(
                'type'    => 'subheading',
                'content' => __z('Facebook comments'),
                'dependency' => array('comments', '==', 'fb')
            ),
            array(
                'id'    => 'fbappid',
                'type'  => 'text',
                'title' => __z('App ID'),
                'subtitle'  => __z('Insert you Facebook app ID'),
                'after' => '<p><a href="https://developers.facebook.com/apps/" target="_blank">'.__z('Facebook developers').'</a></p>',
                'dependency' => array('comments', '==', 'fb')
            ),
            array(
                'id'    => 'fblang',
                'type'  => 'select',
                'title' => __z('APP language'),
                'subtitle'  => __z('Select language for the app of facebook'),
                'options' => array(
                    'af_ZA' => __z('Afrikaans'),
                    'ak_GH' => __z('Akan'),
                    'am_ET' => __z('Amharic'),
                    'ar_AR' => __z('Arabic'),
                    'as_IN' => __z('Assamese'),
                    'ay_BO' => __z('Aymara'),
                    'az_AZ' => __z('Azerbaijani'),
                    'be_BY' => __z('Belarusian'),
                    'bg_BG' => __z('Bulgarian'),
                    'bn_IN' => __z('Bengali'),
                    'br_FR' => __z('Breton'),
                    'bs_BA' => __z('Bosnian'),
                    'ca_ES' => __z('Catalan'),
                    'cb_IQ' => __z('Sorani Kurdish'),
                    'ck_US' => __z('Cherokee'),
                    'co_FR' => __z('Corsican'),
                    'cs_CZ' => __z('Czech'),
                    'cx_PH' => __z('Cebuano'),
                    'cy_GB' => __z('Welsh'),
                    'da_DK' => __z('Danish'),
                    'de_DE' => __z('German'),
                    'el_GR' => __z('Greek'),
                    'en_GB' => __z('English (UK)'),
                    'en_IN' => __z('English (India)'),
                    'en_PI' => __z('English (Pirate)'),
                    'en_UD' => __z('English (Upside Down)'),
                    'en_US' => __z('English (US)'),
                    'eo_EO' => __z('Esperanto'),
                    'es_CL' => __z('Spanish (Chile)'),
                    'es_CO' => __z('Spanish (Colombia)'),
                    'es_ES' => __z('Spanish (Spain)'),
                    'es_LA' => __z('Spanish (Latin America)'),
                    'es_MX' => __z('Spanish (Mexico)'),
                    'es_VE' => __z('Spanish (Venezuela)'),
                    'et_EE' => __z('Estonian'),
                    'eu_ES' => __z('Basque'),
                    'fa_IR' => __z('Persian'),
                    'fb_LT' => __z('Leet Speak'),
                    'ff_NG' => __z('Fulah'),
                    'fi_FI' => __z('Finnish'),
                    'fo_FO' => __z('Faroese'),
                    'fr_CA' => __z('French (Canada)'),
                    'fr_FR' => __z('French (France)'),
                    'fy_NL' => __z('Frisian'),
                    'ga_IE' => __z('Irish'),
                    'gl_ES' => __z('Galician'),
                    'gn_PY' => __z('Guarani'),
                    'gu_IN' => __z('Gujarati'),
                    'gx_GR' => __z('Classical Greek'),
                    'ha_NG' => __z('Hausa'),
                    'he_IL' => __z('Hebrew'),
                    'hi_IN' => __z('Hindi'),
                    'hr_HR' => __z('Croatian'),
                    'hu_HU' => __z('Hungarian'),
                    'hy_AM' => __z('Armenian'),
                    'id_ID' => __z('Indonesian'),
                    'ig_NG' => __z('Igbo'),
                    'is_IS' => __z('Icelandic'),
                    'it_IT' => __z('Italian'),
                    'ja_JP' => __z('Japanese'),
                    'ja_KS' => __z('Japanese (Kansai)'),
                    'jv_ID' => __z('Javanese'),
                    'ka_GE' => __z('Georgian'),
                    'kk_KZ' => __z('Kazakh'),
                    'km_KH' => __z('Khmer'),
                    'kn_IN' => __z('Kannada'),
                    'ko_KR' => __z('Korean'),
                    'ku_TR' => __z('Kurdish (Kurmanji)'),
                    'ky_KG' => __z('Kyrgyz'),
                    'la_VA' => __z('Latin'),
                    'lg_UG' => __z('Ganda'),
                    'li_NL' => __z('Limburgish'),
                    'ln_CD' => __z('Lingala'),
                    'lo_LA' => __z('Lao'),
                    'lt_LT' => __z('Lithuanian'),
                    'lv_LV' => __z('Latvian'),
                    'mg_MG' => __z('Malagasy'),
                    'mi_NZ' => __z('Maori'),
                    'mk_MK' => __z('Macedonian'),
                    'ml_IN' => __z('Malayalam'),
                    'mn_MN' => __z('Mongolian'),
                    'mr_IN' => __z('Marathi'),
                    'ms_MY' => __z('Malay'),
                    'mt_MT' => __z('Maltese'),
                    'my_MM' => __z('Burmese'),
                    'nb_NO' => __z('Norwegian (bokmal)'),
                    'nd_ZW' => __z('Ndebele'),
                    'ne_NP' => __z('Nepali'),
                    'nl_BE' => __z('Dutch (Belgie)'),
                    'nl_NL' => __z('Dutch'),
                    'nn_NO' => __z('Norwegian (nynorsk)'),
                    'ny_MW' => __z('Chewa'),
                    'or_IN' => __z('Oriya'),
                    'pa_IN' => __z('Punjabi'),
                    'pl_PL' => __z('Polish'),
                    'ps_AF' => __z('Pashto'),
                    'pt_BR' => __z('Portuguese (Brazil)'),
                    'pt_PT' => __z('Portuguese (Portugal)'),
                    'qu_PE' => __z('Quechua'),
                    'rm_CH' => __z('Romansh'),
                    'ro_RO' => __z('Romanian'),
                    'ru_RU' => __z('Russian'),
                    'rw_RW' => __z('Kinyarwanda'),
                    'sa_IN' => __z('Sanskrit'),
                    'sc_IT' => __z('Sardinian'),
                    'se_NO' => __z('Northern Sami'),
                    'si_LK' => __z('Sinhala'),
                    'sk_SK' => __z('Slovak'),
                    'sl_SI' => __z('Slovenian'),
                    'sn_ZW' => __z('Shona'),
                    'so_SO' => __z('Somali'),
                    'sq_AL' => __z('Albanian'),
                    'sr_RS' => __z('Serbian'),
                    'sv_SE' => __z('Swedish'),
                    'sw_KE' => __z('Swahili'),
                    'sy_SY' => __z('Syriac'),
                    'sz_PL' => __z('Silesian'),
                    'ta_IN' => __z('Tamil'),
                    'te_IN' => __z('Telugu'),
                    'tg_TJ' => __z('Tajik'),
                    'th_TH' => __z('Thai'),
                    'tk_TM' => __z('Turkmen'),
                    'tl_PH' => __z('Filipino'),
                    'tl_ST' => __z('Klingon'),
                    'tr_TR' => __z('Turkish'),
                    'tt_RU' => __z('Tatar'),
                    'tz_MA' => __z('Tamazight'),
                    'uk_UA' => __z('Ukrainian'),
                    'ur_PK' => __z('Urdu'),
                    'uz_UZ' => __z('Uzbek'),
                    'vi_VN' => __z('Vietnamese'),
                    'wo_SN' => __z('Wolof'),
                    'xh_ZA' => __z('Xhosa'),
                    'yi_DE' => __z('Yiddish'),
                    'yo_NG' => __z('Yoruba'),
                    'zh_CN' => __z('Simplified Chinese (China)'),
                    'zh_HK' => __z('Traditional Chinese (Hong Kong)'),
                    'zh_TW' => __z('Traditional Chinese (Taiwan)'),
                    'zu_ZA' => __z('Zulu'),
                    'zz_TR' => __z('Zazaki')
                ),
                'default' => 'en_US',
                'dependency' => array('comments', '==', 'fb')
            ),
            array(
                'id'    => 'fbadmin',
                'type'  => 'text',
                'title' => __z('Admin user'),
                'subtitle'  => __z('Add user or user ID to manage comment'),
                'dependency' => array('comments', '==', 'fb')
            ),
            array(
                'id'      => 'fbscheme',
                'type'    => 'radio',
                'title'   => __z('Color Scheme'),
                'default' => 'light',
                'options' => array(
                    'light' => __z('Light color'),
                    'dark' => __z('Dark color')
                ),
                'dependency' => array('comments', '==', 'fb')
            ),
            array(
                'id' => 'fbnumber',
                'type' => 'text',
                'title' => __z('Number of Posts'),
                'default' => '10',
                'attributes' => array(
                    'style' => 'width:100px',
                    'type' => 'number'
                ),
                'dependency' => array('comments', '==', 'fb')
            ),
            array(
                'type'    => 'subheading',
                'content' => __z('Disqus comments'),
                'dependency' => array('comments', '==', 'dq')
            ),
            array(
                'id'    => 'dqshortname',
                'type'  => 'text',
                'title' => __z('Shortname'),
                'subtitle'  => __z('This is used to uniquely identify your website on Disqus. It cannot be changed'),
                'after' => '<p><a href="https://help.disqus.com/installation/whats-a-shortname" target="_blank">'.__z('more info').'</a></p>',
                'dependency' => array('comments', '==', 'dq')
            ),
            array(
                'type'    => 'content',
                'content' => '<a href="'.admin_url('options-discussion.php').'"><strong>'.__z('Discussion Settings').'</strong></a>',
                'dependency' => array('comments', '==', 'wp')
            )
        )
    )
);
