<?php
/**
 * Theme acf fields
 *
 * @package fmovie
 */

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_603efa100d159',
	'title' => 'Generator',
	'fields' => array(
		array(
			'key' => 'field_603efa3f589d9',
			'label' => 'Generator',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'postbox noborder',
				'id' => 'Generator',
			),
			'message' => '',
			'new_lines' => '',
			'esc_html' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
	'modified' => false,
));

acf_add_local_field_group(array(
	'key' => 'group_603e7de764b6e',
	'title' => 'Generator Data',
	'fields' => array(
		array(
			'key' => 'field_603e7e3dea9a1',
			'label' => 'Details',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'generator_data',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_603e7e9883aa7',
			'label' => 'IMDb',
			'name' => 'imdb_id',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => 'imdb_id',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_603e820012ecb',
			'label' => 'TMDb',
			'name' => 'id',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => 'id',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_63e3cd80abcb5',
			'label' => 'Original title',
			'name' => 'original_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => 'original_title',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_63e3cd9cabcb6',
			'label' => 'Tagline',
			'name' => 'tagline',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => 'tagline',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_603e84af48412',
			'label' => 'Vote average',
			'name' => 'vote_average',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => 'vote_average',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_63e3ccc4eb29e',
			'label' => 'Vote count',
			'name' => 'vote_count',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => 'vote_count',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_603e85ff905bb',
			'label' => 'Runtime',
			'name' => 'Runtime',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => 'Runtime',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_603e8692248a0',
			'label' => 'Year',
			'name' => 'release_date',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => 'release_date',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_603e87af84162',
			'label' => 'Certification',
			'name' => 'Rated',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => 'Rated',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_63e3ce1904c9f',
			'label' => 'Status',
			'name' => 'status',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => 'status',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_63e3cb09d23e2',
			'label' => 'Popularity',
			'name' => 'popularity',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => 'popularity',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_63e3cb7bd23e4',
			'label' => 'Budget',
			'name' => 'budget',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => 'budget',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_63e3cb41d23e3',
			'label' => 'Revenue',
			'name' => 'revenue',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => 'revenue',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_63e3c64c11d4f',
			'label' => 'Seasons',
			'name' => 'number_of_seasons',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => 'number_of_seasons',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_63e3c5e9cfb27',
			'label' => 'Episodes',
			'name' => 'number_of_episodes',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => 'number_of_episodes',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_63e3cc03f06fd',
			'label' => 'Last air date',
			'name' => 'last_air_date',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => 'last_air_date',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_63e30003f06fe',
			'label' => 'Last episode',
			'name' => 'last_episode_to_air',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => 'last_episode_to_air',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_63e3cc4046032',
			'label' => 'Homepage',
			'name' => 'homepage',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'homepage',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_603e83c0c1660',
			'label' => 'YouTube',
			'name' => 'youtube_id',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'youtube_id',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => 'https://www.youtube.com/watch?v=',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_603e83c0c1779',
			'label' => 'TVDB',
			'name' => 'tvdb_id',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => 'tvdb_id',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_604e83c0c1789',
			'label' => 'MAL',
			'name' => 'mal',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => 'mal',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_605e83c0c1799',
			'label' => 'Anilist',
			'name' => 'anilist',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => 'anilist',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_603e884e60b1c',
			'label' => 'Images',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_603e88ceb5e9c',
			'label' => 'Poster',
			'name' => 'poster_path',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'poster_path',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_603e88e7b5e9d',
			'label' => 'Backdrop',
			'name' => 'backdrop_path',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'backdrop_path',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => 'https://image.tmdb.org/t/p/original',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_603e8b8d42bd6',
			'label' => 'Quality',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_603e8bd146413',
			'label' => 'Select',
			'name' => 'quality',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => 'You can add a new one by clicking on the right of the form.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'quality',
			),
			'taxonomy' => 'quality',
			'field_type' => 'radio',
			'allow_null' => 1,
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'object',
			'multiple' => 0,
		),
		array(
			'key' => 'field_603eb1ea05e75',
			'label' => 'Movies',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 1,
		),
		array(
			'key' => 'field_63765b3ef844c',
			'label' => 'Manual',
			'name' => 'manual_movies',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'Activate manual entry for this movie? (Enabling this option will disable autoembed)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5a6ce58a64da9',
			'label' => 'Servers',
			'name' => 'iframe',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_63765b3ef844c',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5a6ce5c864daa',
			'min' => 0,
			'max' => 5,
			'layout' => 'table',
			'button_label' => 'Add Server',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_5a6ce5c864daa',
					'label' => 'Url',
					'name' => 'server',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '60',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'URL IFRAME',
					'parent_repeater' => 'field_5a6ce58a64da9',
				),
				array(
					'key' => 'field_63763cf08ae32',
					'label' => 'Host',
					'name' => 'host',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'HOST NAME',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_5a6ce58a64da9',
				),
			),
		),
		array(
			'key' => 'field_603eb4e25b59f',
			'label' => 'Series',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_637653c4f0f98',
			'label' => 'Manual',
			'name' => 'manual_tv',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'Activate manual entry for this tv show? (Enabling this option will disable autoembed)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_551980b8a65b5',
			'label' => 'Seasons',
			'name' => 's',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_637653c4f0f98',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_551980eaa65b6',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add season',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_551980eaa65b6',
					'label' => 'Episode',
					'name' => 'e',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Add episode',
					'rows_per_page' => 20,
					'parent_repeater' => 'field_551980b8a65b5',
					'sub_fields' => array(
						array(
							'key' => 'field_637d0cb666c5b',
							'label' => 'Link 1',
							'name' => 'link_1',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Link 1',
							'parent_repeater' => 'field_551980eaa65b6',
						),
						array(
							'key' => 'field_637d0d0b66c5c',
							'label' => 'Host 1',
							'name' => 'host_1',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => 'Server 1',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_551980eaa65b6',
						),
						array(
							'key' => 'field_637d0d1566c5d',
							'label' => 'Link 2',
							'name' => 'link_2',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Link 2',
							'parent_repeater' => 'field_551980eaa65b6',
						),
						array(
							'key' => 'field_637d0d7766c5f',
							'label' => 'Host 2',
							'name' => 'host_2',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => 'Server 2',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_551980eaa65b6',
						),
						array(
							'key' => 'field_637d0d4166c5e',
							'label' => 'Link 3',
							'name' => 'link_3',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Link 3',
							'parent_repeater' => 'field_551980eaa65b6',
						),
						array(
							'key' => 'field_637d0d8266c60',
							'label' => 'Host 3',
							'name' => 'host_3',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => 'Server 3',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_551980eaa65b6',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

endif;		